# Generated by Django 4.1.3 on 2024-01-15 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220518_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='logout',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_price', models.IntegerField()),
                ('offerprice', models.IntegerField()),

            ],
        ),
    ]
