# Generated by Django 4.1.3 on 2024-01-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_logout_offers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logout',
        ),
    ]
