# Generated by Django 4.1.3 on 2024-01-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='hotel_price',
        ),
    ]
