# Generated by Django 4.1.3 on 2024-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_offers_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='discount_price',
            field=models.IntegerField(default=1000),
        ),
    ]
